server:
  port: 8080
  servlet:
    context-path: /security
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernatedb?currentSchema=homework11
    username: postgres
    password: Killthem86
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

